var a = prompt("Nhap a: ");
var b = prompt("Nhap b: ");
var c = prompt("Nhap c: ");
var max=a;
parseInt(a);
parseInt(b);
parseInt(c);
if (b>max) max=b;
if (c>max) max=c;
document.write("Max la: " + max);